name: Node CI

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  validate-and-publish:
    name: Validate and Publish
    runs-on: ubuntu-latest # only linux supported at present
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: npx -p respec respec2html --src index.html --out index.html
