name: Node CI

on:
  push:
    branches:
      - master
  pull_request: {}

env:
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 1
  PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest # only linux supported at present
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: npx -p respec respec2html --src index.html --out index.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          keep_files: true
